name: mindowl
description: "Attention + Time = MindOwl"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_functions: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_crashlytics: ^5.0.0
  firebase_remote_config: ^6.0.0

  # Architecture
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  get_it: ^8.2.0
  event_bus: ^2.0.1
  injectable: ^2.3.2
  fpdart: ^1.1.1
  
  # Services
  permission_handler: ^12.0.1
  whisper_flutter_new: ^1.0.1
  path_provider: ^2.1.4
  record: ^6.0.0


  # Code generation
  freezed_annotation: ^3.0.4
  json_annotation: ^4.9.0

  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  heroicons: ^0.11.0
  flutter_markdown: ^0.7.4+1
  loggy: ^2.0.2
  layou_tools:
    git:
      url: https://github.com/yelkamel/layoutools

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  slang_build_runner: ^4.6.0
  custom_lint:
  envied_generator: ^1.0.1
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17
  very_good_analysis: ^9.0.0
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  mockito: ^5.4.5
  riverpod: any
  test: ^1.25.15
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
    - assets/logo.webp
    - assets/md/
