// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBktAyyHxBTh9aSYWQvA8Nop7ZMkmpJ-E8',
    appId: '1:743937912335:web:0c3716e409b47c9dc27d7a',
    messagingSenderId: '743937912335',
    projectId: 'mindowl-93',
    authDomain: 'mindowl-93.firebaseapp.com',
    storageBucket: 'mindowl-93.firebasestorage.app',
    measurementId: 'G-VF3TFP4D4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQVrqSFfHHZ56xfwcGiQRuqZdSbpjgP2M',
    appId: '1:743937912335:android:5baee162116d6542c27d7a',
    messagingSenderId: '743937912335',
    projectId: 'mindowl-93',
    storageBucket: 'mindowl-93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpFV8PVTisymzQ4leWJi0OTNmvxsYyD3A',
    appId: '1:743937912335:ios:1703d3391fc4fd31c27d7a',
    messagingSenderId: '743937912335',
    projectId: 'mindowl-93',
    storageBucket: 'mindowl-93.firebasestorage.app',
    iosBundleId: 'com.mindowl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpFV8PVTisymzQ4leWJi0OTNmvxsYyD3A',
    appId: '1:743937912335:ios:1703d3391fc4fd31c27d7a',
    messagingSenderId: '743937912335',
    projectId: 'mindowl-93',
    storageBucket: 'mindowl-93.firebasestorage.app',
    iosBundleId: 'com.mindowl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBktAyyHxBTh9aSYWQvA8Nop7ZMkmpJ-E8',
    appId: '1:743937912335:web:571c495252ad6614c27d7a',
    messagingSenderId: '743937912335',
    projectId: 'mindowl-93',
    authDomain: 'mindowl-93.firebaseapp.com',
    storageBucket: 'mindowl-93.firebasestorage.app',
    measurementId: 'G-QTZ7D3DY01',
  );

}